### ISSUE TITLE
ketcindydevelop/master -> masterとして仕切り直し

### ISSUE THREAD

**Issue by munepi** [ketpic/ketcindy#1]
ノルベルトさん @norbusan 、高遠さん @s-takato 、

@s-takato さんが別のリポジトリ https://github.com/ketpic/ketcindydevelop を作ってしまったことと、またまたフォルダ構成が ketcindy/master と異なるので、一度、

 * ketcindy/master -> old-master
 * ketcindy/texlive -> old-texlive

としてしまい、

 * ketcindydevelop/master -> master: import some files from old-master
 * texlive:  import some files from old-texlive

としようと思います。

要するに、新しいフォルダ構成で仕切り直しです ;-) 

こちらで、その作業をやってしまい、現状に追従してしまおうと思います。いかがでしょうか？

**Comment by norbusan** [comment]
了解です！できましたら連絡ください、僕はpullします。できるだけ今週のミーティングの前。。。
よろしくお願いします。

**Comment by munepi** [comment]
@norbusan さん＞

> 了解です！できましたら連絡ください、
> 僕はpullします。できるだけ今週のミーティングの前。。。

ひと通り、本作業ができました。

ありがとうございます。
引き続き、Darwinに関する変更点があれば、 texlive branch に push しますね!!



@s-takato さん＞
最新の ketpic/ketcindydevelop リポジトリの master ブランチを、
こちらの ketpic/ketcindy リポジトリの master ブランチとして、ほぼそのまま取り込みました。

今後は、こちらの ketpic/ketcindy リポジトリの master ブランチに変更点を push くださいませ。
どうかどうか、よろしくお願いいたします。

**Comment by munepi** [comment]
@norbusan @s-takato 
先日の作業を経て、commit 509f41f で ketcindy on KeTTeX が動いていることを確認できました。

**Comment by munepi** [comment]
closed #1 via commit 509f41f
