### ISSUE TITLE
DircdyにkpsewhichからTEXMFDIST/scripts/ketcindyを予め与えられるかどうか。

### ISSUE THREAD

**Issue by munepi** [ketpic/ketcindy#2]
現時点で Dirhead を固定的に与えておかないと動かないように見えるので、報告します（メールだと埋もれるので）。

現時点で `TEXMFDIST/scripts/ketcindy/dirhead.txt` は、以下のようになっています。

``` cindyscript
Dirhead=Dircdy;
Dirwork=gethome()+pathsep()+"ketcindy";
Dircdy=Dirwork;
setdirectory(Dirhead);
import("setketcindy.txt");
import("ketoutset.txt");
setdirectory(Dirwork);
```

`/Applications/Cinderella2.app/Contents/PlugIns/dirhead.txt` が存在しない状態では、
[nodirhead.log](https://github.com/ketpic/ketcindy/files/1914228/nodirhead.log) のようになりました。
この log ファイルのとおり、 `TEXMFDIST/scripts/ketcindy/` を探しにいっているものの、 `TEXMFDIST/scripts/ketcindy/ketlib` まで見に行っていないようです。

一方、 `Dirhead=TEXMFDIST/scripts/ketcindy/dirhead.txt` を固定的に与えていると、ここでは、 `/Applications/Cinderella2.app/Contents/PlugIns/dirhead.txt`  で与えてみますと、
[usedirhead.log](https://github.com/ketpic/ketcindy/files/1914236/usedirhead.log) のようになりました。

``` cindyscript
//Dirhead=Dircdy; // println([1,Dirhead,Dircdy]);
Dirhead="TEXMFDIST/scripts/ketcindy"; // これがないと動かない。
// jarからkpsewhichを走らせて、Dircdyに値をあらかじめ入れられないかな？
```

jar側から、もしくは、CindyScript から os のsystem 側から  `kpsewhich` を走らせて、`Dircdy` に値を与えられないでしょうか？

もしくは、jar側から Dirketcdy を kpsewhich から引っ張ってきて、 Dirketcdyが空でなければ、Dircdy に代入するなど。

**Comment by norbusan** [comment]
うん、問題はどうやってTEXMFDISTを得られますか。
僕はいろんなことを探しましたが、Cindyからできないと思います。Javaならばできると思います。
